
--
-- 2015-03-21 dbrown : Created (ported from MS=SQL)
-- 

create or replace function insert_ipn
(
    _business          varchar(50)  default NULL, 
    _receiver_email    varchar(50)  default NULL,
    _item_name         varchar(50)  default NULL,     
    _item_number       varchar(50)  default NULL,     
    _quantity          int          default NULL, 
    _invoice           varchar(50)  default NULL,  
    _custom            varchar(50)  default NULL,  
    _memo              varchar(50)  default NULL, 
    _tax               money        default NULL, 
    _payment_status    varchar(50)  default NULL, 
    _pending_reason    varchar(50)  default NULL, 
    _reason_code       varchar(50)  default NULL, 
    _payment_date      varchar(50)  default NULL, 
    _txn_id            varchar(50)  default NULL,
    _txn_type          varchar(50)  default NULL, 
    _payment_type      varchar(50)  default NULL, 
    _mc_gross          money        default NULL, 
    _mc_fee            money        default NULL, 
    _mc_currency       char(3)      default NULL, 
    _settle_amount     money        default NULL,
    _settle_currency   varchar(50)  default NULL, 
    _exchange_rate     float        default NULL,  
    _payment_gross     money        default NULL, 
    _payment_fee       money        default NULL, 
    _subscr_date       varchar(50)  default NULL, 
    _subscr_effective  varchar(50)  default NULL, 
    _period1           varchar(50)  default NULL, 
    _period2           varchar(50)  default NULL, 
    _period3           varchar(50)  default NULL, 
    _amount1           money        default NULL, 
    _amount2           money        default NULL, 
    _amount3           money        default NULL,
    _mc_amount1        money        default NULL, 
    _mc_amount2        money        default NULL, 
    _mc_amount3        money        default NULL, 
    _recurring         char(1)      default NULL, 
    _reattempt         char(1)      default NULL, 
    _retry_at          varchar(50)  default NULL,
    _recur_times       int          default NULL, 
    _username          varchar(50)  default NULL, 
    _password          varchar(50)  default NULL,  
    _subscr_id         varchar(50)  default NULL, 
    _first_name        varchar(50)  default NULL, 
    _last_name         varchar(50)  default NULL,
    _address_name      varchar(50)  default NULL, 
    _address_street    varchar(50)  default NULL, 
    _address_city      varchar(50)  default NULL, 
    _address_state     varchar(50)  default NULL, 
    _address_zip       varchar(50)  default NULL,
    _address_country   varchar(50)  default NULL, 
    _address_status    varchar(50)  default NULL, 
    _payer_email       varchar(50)  default NULL, 
    _payer_id          varchar(50)  default NULL, 
    _payer_status      varchar(50)  default NULL,
    _notify_version    varchar(8)   default NULL, 
    _verify_sign       varchar(200) default NULL, 
    _post_status       varchar(50)  default NULL, 
    _post_response     varchar(50)  default NULL
) returns int as $$

declare

    EVENT_DEVERR_ADDING_IPN constant char(4) = '9140';
    RETVAL_ERR_EXCEPTION int = -98;

begin

    declare errno text; errmsg text; errdetail text;
    begin -- 'Try'

        insert into ipn (
            business,
            IPNReceived, 
            receiver_email,     
            item_name,     
            item_number,     
            quantity, 
            invoice,  
            custom,  
            memo, 
            tax, 
            payment_status, 
            pending_reason, 
            reason_code, 
            payment_date, 
            txn_id,
            txn_type, 
            payment_type, 
            mc_gross, 
            mc_fee, 
            mc_currency, 
            settle_amount,
            settle_currency, 
            exchange_rate,  
            payment_gross, 
            payment_fee, 
            subscr_date, 
            subscr_effective, 
            period1, 
            period2, 
            period3, 
            amount1, 
            amount2, 
            amount3,
            mc_amount1, 
            mc_amount2, 
            mc_amount3, 
            recurring, 
            reattempt, 
            retry_at,
            recur_times, 
            username, 
            password,  
            subscr_id, 
            first_name, 
            last_name,
            address_name, 
            address_street, 
            address_city, 
            address_state, 
            address_zip,
            address_country, 
            address_status, 
            payer_email, 
            payer_id, 
            payer_status,
            notify_version, 
            verify_sign, 
            post_status, 
            post_response
        ) values (
            _business,
            cast( now() as timestamp ), 
            _receiver_email,     
            _item_name,     
            _item_number,     
            _quantity, 
            _invoice,  
            _custom,  
            _memo, 
            _tax, 
            _payment_status, 
            _pending_reason, 
            _reason_code, 
            _payment_date, 
            _txn_id,
            _txn_type, 
            _payment_type, 
            _mc_gross, 
            _mc_fee, 
            _mc_currency, 
            _settle_amount,
            _settle_currency, 
            _exchange_rate,  
            _payment_gross, 
            _payment_fee, 
            _subscr_date, 
            _subscr_effective, 
            _period1, 
            _period2, 
            _period3, 
            _amount1, 
            _amount2, 
            _amount3,
            _mc_amount1, 
            _mc_amount2, 
            _mc_amount3, 
            _recurring, 
            _reattempt, 
            _retry_at,
            _recur_times, 
            _username, 
            _password,  
            _subscr_id, 
            _first_name, 
            _last_name,
            _address_name, 
            _address_street, 
            _address_city, 
            _address_state, 
            _address_zip,
            _address_country, 
            _address_status, 
            _payer_email, 
            _payer_id, 
            _payer_status,
            _notify_version, 
            _verify_sign, 
            _post_status, 
            _post_response
        );

    exception when others then

            get stacked diagnostics errno=RETURNED_SQLSTATE, errmsg=MESSAGE_TEXT, errdetail=PG_EXCEPTION_DETAIL;
            perform log_event(null, null, EVENT_DEVERR_ADDING_IPN, '['||errno||'] '||errmsg||' : '||errdetail );   
            return RETVAL_ERR_EXCEPTION;
    end;

    return lastval(); 
end;
$$ language plpgsql;

