
/* table-ipn.sql : FIXME 

CODE TO BE PORTED:

CREATE TABLE [dbo].[IPN](
    [UID] [int] IDENTITY(1,1) NOT NULL,
    [IPNReceived] [datetime] NULL,
    [business] [varchar](50) NULL,
    [receiver_email] [varchar](50) NULL,
    [item_name] [varchar](127) NULL,
    [item_number] [varchar](127) NULL,
    [quantity] [int] NULL,
    [invoice] [varchar](50) NULL,
    [custom] [varchar](50) NULL,
    [memo] [varchar](50) NULL,
    [tax] [money] NULL,
    [payment_status] [varchar](50) NULL,
    [pending_reason] [varchar](50) NULL,
    [reason_code] [varchar](50) NULL,
    [payment_date] [varchar](50) NULL,
    [txn_id] [varchar](50) NULL,
    [txn_type] [varchar](50) NULL,
    [payment_type] [varchar](50) NULL,
    [mc_gross] [money] NULL,
    [mc_fee] [money] NULL,
    [mc_currency] [char](3) NULL,
    [settle_amount] [money] NULL,
    [settle_currency] [varchar](50) NULL,
    [exchange_rate] [float] NULL,
    [payment_gross] [money] NULL,
    [payment_fee] [money] NULL,
    [subscr_date] [varchar](50) NULL,
    [subscr_effective] [varchar](50) NULL,
    [period1] [varchar](50) NULL,
    [period2] [varchar](50) NULL,
    [period3] [varchar](50) NULL,
    [amount1] [money] NULL,
    [amount2] [money] NULL,
    [amount3] [money] NULL,
    [mc_amount1] [money] NULL,
    [mc_amount2] [money] NULL,
    [mc_amount3] [money] NULL,
    [recurring] [char](1) NULL,
    [reattempt] [char](1) NULL,
    [retry_at] [varchar](50) NULL,
    [recur_times] [int] NULL,
    [username] [varchar](50) NULL,
    [password] [varchar](50) NULL,
    [subscr_id] [varchar](50) NULL,
    [first_name] [varchar](50) NULL,
    [last_name] [varchar](50) NULL,
    [address_name] [varchar](50) NULL,
    [address_street] [varchar](50) NULL,
    [address_city] [varchar](50) NULL,
    [address_state] [varchar](50) NULL,
    [address_zip] [varchar](50) NULL,
    [address_country] [varchar](50) NULL,
    [address_status] [varchar](50) NULL,
    [payer_email] [varchar](50) NULL,
    [payer_id] [varchar](50) NULL,
    [payer_status] [varchar](50) NULL,
    [notify_version] [varchar](8) NULL,
    [verify_sign] [varchar](200) NULL,
    [post_status] [varchar](50) NULL,
    [post_response] [varchar](50) NULL,
    [HAStatus] [varchar](8) NULL,
 CONSTRAINT [PK_IPN] PRIMARY KEY CLUSTERED ([UID] ASC)
*/
